import React, { useState } from "react"

const Search = ({ setQuery }) => {
  // a handler function to handle events generated by the input field such as e.target.value that 
  // gets the content of the input field
  const handler = (e) => {
    // prevent default form behavior
    e.preventDefault();
    // Set the query to the value of the content of the input box
    setQuery(e.target.value)
  }

  // Return an input field that triggers a function when clicking on the enter key in the keyboard
  return (
    <>
      <input className="search" type="text"
        placeholder="Search for Russia, Japan..."
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            handler(e)
          }
        }}
      />
    </>
  )
}

export default Search
